---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: egs-conv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:8.0
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
      #   volumeMounts:
      #   - name: mysql-config-volume
      #     mountPath: /docker-entrypoint-initdb.d/data.sql
      # volumes:
      # - name: mysql-config-volume
      #   hostPath:
      #     path: ./mysql/config.sql
      #     type: File
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  namespace: egs-conv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: rmohr/activemq:5.15.9
        envFrom:
          - secretRef:
              name: activemq-secrets
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8161
        - containerPort: 61616
        - containerPort: 61613

---
