
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: egs-conv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-deployment
  template:
    metadata:
      labels:
        app: notification-deployment
    spec:
      containers:
      - name: notification-deployment
        image: registry.deti:5000/egs-conv/notification-service:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: localstack-secrets
          secret:
            secretName: localstack-secrets
        - name: activemq-secrets
          secret:
            secretName: activemq-secrets
        - name: localstack-configmap
          configMap:
            name: localstack-configmap
        - name: activemq-configmap
          configMap:
            name: activemq-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: egs-conv
spec:
  ports:
  - name: http
    port: 80 # Required Value, not used
  selector:
    app: notification-deployment
---