apiVersion: v1
kind: ConfigMap
metadata:
  name: composer-debug-conf
  namespace: egs-conv
data:
  debug.py: |
    import socket
    import logging
    logging.basicConfig(level=logging.INFO)

    def dns_check(domain):
        try:
            ip_address = socket.gethostbyname(domain)
            logging.info(f"DNS resolution successful. {domain} resolves to {ip_address}")
        except socket.gaierror as e:
            logging.error(f"DNS resolution failed for {domain}. Error: {str(e)}")

    # Example usage
    if __name__ == '__main__':
      dns_check("activemq-service.egs-conv.svc.cluster.local")
