---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: egs-conv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
      - name: web-deployment
        image: registry.deti:5000/egs-conv/web-service:v1
        env:
          - name: REACT_APP_PROXY_URL
            value: http://traefik:80
          - name: APP_COOKIE_NAME
            value: MY_SUPER_COOOKIE
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: egs-conv
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: web-deployment
---